name: "auto check and update"

on:
  push:
    branches:
      - 'master'
#  schedule:
#    - cron: "0 2 * * 1"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.4
      - run: pip install requests gitpython
      - name: Check and Update
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          git config --global user.name "quizhizhe"
          git config --global user.email "42761326+quizhizhe@users.noreply.github.com"
          python scripts/checkLLRelease.py
#          git submodule update --init --recursive --remote
#          git commit -am "fetch upstream SDK" || exit 0
          git push || exit 0
          git push origin --tags
#      - name: Push changes
#        uses: ad-m/github-push-action@master
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          branch: ${{ github.ref }}
#          force: true
#          tags: true
