name: "auto check and update"

on:
  push:
    branches:
      - 'test-autoRelease'
#  schedule:
#    - cron: "10 1 * * *"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.4
      - run: pip install requests gitpython
      - name: Check and Update
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          python scripts/checkLLRelease.py
          git submodule update --init --recursive --remote
          git push || exit 0
          git push origin --tags
#        shell: bash
#      - name: Push changes
#        uses: ad-m/github-push-action@master
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          branch: ${{ github.ref }}
#          force: true
#          tags: true